# Recent Holiday Trends and Traveller Behaviour Survey

## The purpose of this survey is to explore recent holiday trends and traveller behaviour. This survey forms part of an academic project for the Statistical Techniques for Data Analytics module.

In [8]:
import pandas as pd

In [9]:
# Load the Holiday Trends Dataset
df_Holidays = pd.read_csv("Holiday_trends_Data_CA1.csv")

# Display first 10 rows
df_Holidays.head(5)

,Timestamp,What age range are you in,Was your holiday,What was the main purpose of your Holiday,How did you book your holiday,How recent was this holiday,How would you describe your holiday type,How many people were in your travel group?,Approximately how much did your accommodation cost per room per night (€)?,How many nights did your holiday last?,"Overall Holiday Cost - Approximate total spend for all travellers (€), including cost of holiday + daily spending.",\nHow satisfied were you with your holiday overall?,Would You Take This Type of Holiday Again?,Did You Travel by Air?,\nHow many holidays have you taken in the last 12 months?
0,25/09/2026 12:25,65+,A Holiday abroad (outside Ireland),"To attend an event (concert, Football match etc)",Independently Booked online,Greater than 3 months ago but within the last ...,A holiday with friends,6,100,3,800,5,Yes,Yes,2
1,25/09/2026 12:25,55-64,A Holiday abroad (outside Ireland),Beach Holiday abroad,A package holiday,In last 3 months,A family holiday,2,150,5,3000,3,Yes,Yes,3
2,25/09/2026 12:27,65+,A Holiday abroad (outside Ireland),Beach Holiday abroad,Independently Booked online,In last 3 months,A family holiday,4,70,28,4800,5,Yes,No,4
3,25/09/2026 12:29,65+,A Holiday abroad (outside Ireland),City Break,Independently Booked online,Greater than 3 months ago but within the last ...,A holiday with friends,6,50,3,500,5,Yes,Yes,2
4,25/09/2026 12:32,25-34,A Holiday abroad (outside Ireland),Other,Independently Booked online,Greater than 3 months ago but within the last ...,A holiday with friends,3,115,6,3000,5,Yes,Yes,3

In [10]:
# Show info on the csv file
df_Holidays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 15 columns):
 #   Column                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                               --------------  -----
 0   Timestamp                                                                                                            44 non-null     object
 1   What age range are you in                                                                                            44 non-null     object
 2   Was your holiday                                                                                                     44 non-null     object
 3   What was the main purpose of your Holiday                                                                            44 non-null     object
 4   How did you book your holiday                                                                                        44 non-null     object
 5   How recent was this holiday                                                                                          44 non-null     object
 6   How would you describe your holiday type                                                                             44 non-null     object
 7   How many people were in your travel group?                                                                           44 non-null     int64
 8   Approximately how much did your accommodation cost per room per night (€)?                                           44 non-null     int64
 9   How many nights did your holiday last?                                                                               44 non-null     int64
 10  Overall Holiday Cost - Approximate total spend for all travellers (€), including  cost of holiday + daily spending.  44 non-null     int64
 11
How satisfied were you with your holiday overall?                                                                   44 non-null     int64
 12  Would You Take This Type of Holiday Again?                                                                           44 non-null     object
 13  Did You Travel by Air?                                                                                               44 non-null     object
 14
How many holidays have you taken in the last 12 months?                                                             44 non-null     int64
dtypes: int64(6), object(9)
memory usage: 5.3+ KB

In [11]:
df_Holidays.describe().T

,count,mean,std,min,25%,50%,75%,max
How many people were in your travel group?,44.0,3.295455,1.636496,1.0,2.0,3.0,4.00,9.0
Approximately how much did your accommodation cost per room per night (€)?,44.0,231.886364,599.976558,10.0,80.0,117.5,150.00,4000.0
How many nights did your holiday last?,44.0,7.431818,5.820564,2.0,4.0,6.0,7.25,28.0
"Overall Holiday Cost - Approximate total spend for all travellers (€), including cost of holiday + daily spending.",44.0,2420.454545,1646.324948,400.0,1000.0,2000.0,3000.00,6000.0
\nHow satisfied were you with your holiday overall?,44.0,4.454545,0.663134,3.0,4.0,5.0,5.00,5.0
\nHow many holidays have you taken in the last 12 months?,44.0,2.522727,1.171138,1.0,2.0,2.0,3.00,5.0